### ISSUE TITLE
No such file or directory Error.

### ISSUE THREAD

**Issue by Musab1337** [Miladkhoshdel/burp-to-sqlmap#1]
Hi there! 

I really appreciate this work, i noticed this error while I'm testing burp-to-sqlmap.py:

root@PenTesTer:~/burp-to-sqlmap# python burp-to-sqlmap.py  -f sqli.txt -o rus -s /usr/share/sqlmap/

 #######################################################################
 #                                                                     #
 #  \______   \    |   \______   \______   \ \__    ___/\_____  \      #
 #   |    |  _/    |   /|       _/|     ___/   |    |    /   |   \     #
 #   |    |   \    |  / |    |   \|    |       |    |   /    |    \    #
 #   |______  /______/  |____|_  /|____|       |____|   \_______  /    #
 #          \/                 \/                               \/     #
 #    _________________  .____       _____      _____ __________       #
 #   /   _____/\_____  \ |    |     /     \    /  _  \\______   \      #
 #   \_____  \  /  / \  \|    |    /  \ /  \  /  /_\  \|     ___/      #
 #   /        \/   \_/.  \    |___/    Y    \/    |    \    |          #
 #  /_______  /\_____\ \_/_______ \____|__  /\____|__  /____|          #
 #          \/        \__>       \/       \/         \/                #
 #                                                                     #
 #    Created By: Milad Khoshdel      Blog: https://blog.regux.com     #
 #                                    E-Mail: miladkhoshdel@gmail.com  #
 #######################################################################

 [+] Exporting Packets ...
   [-] Packet 1 Exported.
   [-] Packet 2 Exported.
   [-] Packet 3 Exported.
   [-] Packet 4 Exported.
   [-] Packet 5 Exported.
   [-] Packet 6 Exported.
   [-] Packet 7 Exported.
   [-] Packet 8 Exported.
   [-] Packet 9 Exported.
   [-] Packet 10 Exported.
   [-] Packet 11 Exported.
   [-] Packet 12 Exported.
   [-] Packet 13 Exported.
   [-] Packet 14 Exported.
   [-] Packet 15 Exported.
   [-] Packet 16 Exported.
   [-] Packet 17 Exported.
   [-] Packet 18 Exported.
   [-] Packet 19 Exported.
   [-] Packet 20 Exported.
   [-] Packet 21 Exported.
   [-] Packet 22 Exported.
   [-] Packet 23 Exported.
   [-] Packet 24 Exported.
   [-] Packet 25 Exported.

25 Packets Exported Successfully.

 [+] Testing SQL Injection on packets ...  (Based on your network connection Test can take up to 5 minutes.)
   [-] Performing SQL Injection on packet number 4. Please Wait ...
Traceback (most recent call last):
  File "burp-to-sqlmap.py", line 90, in <module>
    if 'is vulnerable' in open(directory + "\\testresult" + file).read() or "Payload:" in open(
IOError: [Errno 2] No such file or directory: 'rus\\testresult4.txt'
root@PenTesTer:~/burp-to-sqlmap#uname -a 
Linux PenTesTer 4.9.0-kali3-amd64 #1 SMP Debian 4.9.18-1kali1 (2017-04-04) x86_64 GNU/Linux

I also create a file with testresult4.txt in rus directory, didn't fix the iusse.

**Comment by Miladkhoshdel** [comment]
Hello,
What is the path you run script in ? is bellow directory accessible from your path ?
rus\testresult4.txt
and maybe you have another rus directory in your / path. please check it out too and let me know about the result.

**Comment by jaikishantulswani** [comment]
I am also getting the same even when the directory new and the file of saved burp request are at the same place.

`
+] Testing SQL Injection on packets ...  (Based on your network connection Test can take up to 5 minutes.)
   [-] Performing SQL Injection on packet number 8. Please Wait ...
Traceback (most recent call last):
  File "burp-to-sqlmap.py", line 90, in <module>
    if 'is vulnerable' in open(directory + "\\testresult" + file).read() or "Payload:" in open(
IOError: [Errno 2] No such file or directory: 'new\\testresult8.txt'
`

**Comment by Miladkhoshdel** [comment]
@jaikishantulswani 
What is your OS ? What version of python installed on your OS ? also please send me 8.txt file for checking your problem with more details.

**Comment by jacampb** [comment]
> @Miladkhoshdel
> I am also getting the same even when the directory new and the file of saved burp request are at the same place.
> 
> `+] Testing SQL Injection on packets ... (Based on your network connection Test can take up to 5 minutes.) [-] Performing SQL Injection on packet number 8. Please Wait ... Traceback (most recent call last): File "burp-to-sqlmap.py", line 90, in <module> if 'is vulnerable' in open(directory + "\\testresult" + file).read() or "Payload:" in open( IOError: [Errno 2] No such file or directory: 'new\\testresult8.txt'`

I had also ran in to this with consecutive runs without clearing out the last runs files. It's been a minute, but if I remember correctly it was when the call to sqlmap fails because it picked up an old file with the SQLmap header as mentioned above, no result file was created and the subsequent call to search the result file for 'is vulnerable' freaks out.

**Comment by jaikishantulswani** [comment]
@Miladkhoshdel 

OS : Kali
Python 2.7.15+

Execution : python burp-to-sqlmap.py -f burprequest -o result -s /usr/share/sqlmap/

Error:
`[+] Testing SQL Injection on packets ...  (Based on your network connection Test can take up to 5 minutes.)
   [-] Performing SQL Injection on packet number 1. Please Wait ...
Traceback (most recent call last):
  File "burp-to-sqlmap.py", line 90, in <module>
    if 'is vulnerable' in open(directory + "\\testresult" + file).read() or "Payload:" in open(
IOError: [Errno 2] No such file or directory: 'result\\testresult1.txt'
`
There is only 1.txt file inside result folder but not testresult1.txt
1.txt is attached here.
[1.txt](https://github.com/Miladkhoshdel/burp-to-sqlmap/files/2792906/1.txt)

**Comment by jacampb** [comment]
This script only supports windows at the moment I believe. There is a pull request pending to add linux support, it will need reviewed by @Miladkhoshdel to determine if it meets the criteria to be merged.

**Comment by Miladkhoshdel** [comment]
Script Support Linux And Windows Now
