### ISSUE TITLE
Script does not clear the output

### ISSUE THREAD

**Issue by Miladkhoshdel** [Miladkhoshdel/burp-to-sqlmap#3]
I experienced this during concsecutive runs. Currently the script does not clear the output directory before starting a  fresh run so all the old files are still there and are read in as request files. The symbols you are seeing are the banner for sqlmap, one line at a time due to old testresult files being processed as new request files.

_Originally posted by @jacampb in https://github.com/Miladkhoshdel/burp-to-sqlmap/issues/1#issuecomment-447686379_

**Comment by Miladkhoshdel** [comment]
Script Supports Windows and Linux now. Try again and let me know if the problem exists.

**Comment by D0cK3rG33k** [comment]
yeshh script not work not clear the output

**Comment by Miladkhoshdel** [comment]
Sorry for the delay in responding. does your problem exists yet ? iwould you please explain what is the problem. do you have any error logs ?

**Comment by Miladkhoshdel** [comment]
Main Script Updated. Check it Again and let me know if you faced unclear output again.

**Comment by Miladkhoshdel** [comment]
> 
> 
> yeshh script not work not clear the output

Main Script Updated. Check it Again and let me know if you faced unclear output again.
