### ISSUE TITLE
how to add '--level'/'--risk' and '--tamper'

### ISSUE THREAD

**Issue by abidi12** [Miladkhoshdel/burp-to-sqlmap#5]
Hi,

how to add '--level'/'--risk' and '--tamper'

**Comment by Miladkhoshdel** [comment]
Hello,

--risk and --level option has been added to script. you can use it now.
Also I have some plan for adding --tamper option too.

**Comment by Miladkhoshdel** [comment]
--tamper has been added to Script. Thank you for your suggestion for improvement
